database:
    image: postgres:9.6
    ports:
        - "5432:5432"

router:
    image: nginx
    ports:
        - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
        - api

api:
    image: vlkdev/k8sapp-api:latest
    command: --reload
    volumes:
        - ./api:/app
    links:
        - database
