apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: vlkdev/k8sapp-api
        ports:
          - containerPort: 8000
            protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
  - protocol: TCP
    port: 8000
  selector:
    app: api

